In [6]:
import numpy as np
from csv import DictReader 


def getG(thetax):
    return (1 / (1 + np.exp(-1 * thetax)))

def batchGradientDescent(x, y, theta, numIterations,alpha):
    xTrans = np.transpose(x)
    m = len(x)
    for i in range(0, numIterations):
        hypothesis = getG(np.dot(x, theta))
        loss = hypothesis - y
        gradient = np.dot(xTrans, loss) / m
        theta = theta - alpha * gradient
    return theta



def extract():
    file = open('/content/data.csv', 'r')
    reduced_dict = DictReader(file)
    x = []
    y = []

    for i in reduced_dict:
        x.append([1.0,float(i['Exam 1']),float(i['Exam 2 '])])
        y.append([float(i['Pass/Fail'])])

    x_train = []
    y_train = []
    x_test = []
    y_test = []

    for i in range(len(x)):
        if len(x_train) < 0.7 * len(x):
            x_train.append(x[i])
            y_train.append(y[i])
        else:
            x_test.append(x[i])
            y_test.append(y[i])
    return x_train, y_train, x_test, y_test


x_train,y_train,x_test,y_test = extract()


ones = np.ones((len(x_test),1))
theta = [[1],[1],[1]]



num_iterations = 1000
alpha =0.0000001
print("without feature scaling Batch Gradient Descent is :  ")
theta= batchGradientDescent(x_train,y_train,theta,num_iterations,alpha)
print(theta)

y_pred = getG(np.dot(x_test,theta)) 

for i in range(len(y_pred)):
    if(y_pred[i]>= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
error = 0 

for i in range(len(y_pred)):
    if y_pred[i] != y_test[i]:
        print(y_pred[i],y_test[i])
        error = error+1
error = error/len(y_test)*100

print("And the  %age error is : ",error,"%")

def featureScaling(x_train):

    min_x1 = x_train[0][1]
    min_x2 = x_train[0][2]

    max_x1 = x_train[0][1]
    max_x2 = x_train[0][2]

    x_train_scaled = x_train

    avg_x1 = 0
    avg_x2 = 0

    for i in range(len(x_train)):
        min_x1 = min(x_train[i][1],min_x1)
        min_x2 = min(x_train[i][2],min_x2)

        avg_x1 += x_train[i][1]
        avg_x2 += x_train[i][2]

        max_x1 = max(x_train[i][1],max_x1)
        max_x2 = max(x_train[i][2],max_x2) 

    avg_x1 = avg_x1/len(x_train)
    avg_x2 = avg_x2/len(x_train)

    for i in range(len(x_train_scaled)):
        x_train_scaled[i][1] = (x_train_scaled[i][1] - avg_x1)/(max_x1-min_x1)
        x_train_scaled[i][2] = (x_train_scaled[i][2] - avg_x2)/(max_x2-min_x2)
    return x_train_scaled


print("with feature scaling Batch Gradient Descent  is : ")
x_train_scaled = featureScaling(x_train)
theta = [[1],[1],[1]]
print(x_train_scaled)

theta= batchGradientDescent(x_train_scaled,y_train,theta,num_iterations,alpha)
print(theta)

y_pred = getG(np.dot(x_test,theta)) 

for i in range(len(y_pred)):
    if(y_pred[i]>= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
error = 0 

for i in range(len(y_pred)):
    if y_pred[i] != y_test[i]:
        print(y_pred[i],y_test[i])
        error = error+1
error = error/len(y_test)*100
print("And the  %age error is ",error,"%")

without feature scaling Batch Gradient Descent is :  
[[0.99995143]
 [0.99749146]
 [0.99731272]]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
And the  %age error is :  20.0 %
with feature scaling Batch Gradient Descent  is : 
[[1.0, -0.42248191383243333, 0.20129978609183655], [1.0, -0.48514217573552515, -0.29865054135621977], [1.0, -0.40480117908208313, 0.12626269815125174], [1.0, -0.053206205184509116, 0.3226462593950899], [1.0, 0.2191406775841619, 0.1620370549110696], [1.0, -0.2713612948945694, -0.11669549974054327], [1.0, -0.039855306588017794, 0.4721035001464361], [1.0, 0.16123320810088704, -0.2596998294262299], [1.0, 0.17675096051811776, 0.33893569791366374], [1.0, 0.29716112094246266, -0.30394751636894696], [1.0, 0.46228355147646827, -0.3817036736988813], [1.0, 0.1610730204605449, -0.4933550897627231], [1.0, 0.2664480330363781, 0.17870104555494756], [1.0, 0.07945522998911655, 0.4897881898779887], [1.0, -0.35147459588978297, 0.1721802105112837], [1.0, -0.14295

In [4]:
import numpy as np
from csv import DictReader 

def extract():
    file = open('/content/data.csv', 'r')
    reduced_dict = DictReader(file)
    x = []
    y = []

    for i in reduced_dict:
        x.append([1.0,float(i['Exam 1']),float(i['Exam 2 '])])
        y.append([float(i['Pass/Fail'])])

    x_train = []
    y_train = []
    x_test = []
    y_test = []

    for i in range(len(x)):
        if len(x_train) < 0.7 * len(x):
            x_train.append(x[i])
            y_train.append(y[i])
        else:
            x_test.append(x[i])
            y_test.append(y[i])
    return x_train, y_train, x_test, y_test

def getG(thetax):
    return (1 / (1 + np.exp(-1 * thetax)))

def miniBatchGradientDescent(x, y, theta, numIterations,alpha):
    batchSize = 10
    # xTrans = np.transpose(x)
    m = len(x)
    for i in range(0, numIterations):
        for j in range(0,(int)(len(x)/batchSize)):
            start = batchSize*j
            end = batchSize*j + batchSize
            X = x[start:end]
            Y = y[start:end]
            xTrans = np.transpose(X)
            hypothesis = getG(np.dot(X, theta))
            loss = hypothesis - Y
            gradient = np.dot(xTrans, loss) / m
            theta = theta - alpha * gradient
    return theta

x_train,y_train,x_test,y_test = extract()

ones = np.ones((len(x_test),1))
theta = [[1],[1],[1]]

num_iterations = 1000
alpha =0.001
print("Mini Batch Gradient Descent (without feature scaling)")
theta= miniBatchGradientDescent(x_train,y_train,theta,num_iterations,alpha)
print(theta)

y_pred = getG(np.dot(x_test,theta)) 

for i in range(len(y_pred)):
    if(y_pred[i]>= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
error = 0 

for i in range(len(y_pred)):
    if y_pred[i] != y_test[i]:
        print(y_pred[i],y_test[i])
        error = error+1
error = error/len(y_test)*100

print("Error %age: ",error,"%")

def featureScaling(x_train):

    min_x1 = x_train[0][1]
    min_x2 = x_train[0][2]

    max_x1 = x_train[0][1]
    max_x2 = x_train[0][2]

    x_train_scaled = x_train

    avg_x1 = 0
    avg_x2 = 0

    for i in range(len(x_train)):
        min_x1 = min(x_train[i][1],min_x1)
        min_x2 = min(x_train[i][2],min_x2)
        # min_x3 = min(x_train[i][3],min_x3)

        avg_x1 += x_train[i][1]
        avg_x2 += x_train[i][2]
        # avg_x3 += x_train[i][3]

        max_x1 = max(x_train[i][1],max_x1)
        max_x2 = max(x_train[i][2],max_x2)
        # max_x3 = max(x_train[i][3],max_x3) 

    avg_x1 = avg_x1/len(x_train)
    avg_x2 = avg_x2/len(x_train)
    # avg_x3 = avg_x3/len(x_train)

    for i in range(len(x_train_scaled)):
        x_train_scaled[i][1] = (x_train_scaled[i][1] - avg_x1)/(max_x1-min_x1)
        x_train_scaled[i][2] = (x_train_scaled[i][2] - avg_x2)/(max_x2-min_x2)
        # x_train_scaled[i][3] = (x_train_scaled[i][3] - avg_x3)/(max_x3-min_x3)
    return x_train_scaled


print("Mini Batch Gradient Descent (with feature scaling)")
x_train_scaled = featureScaling(x_train)
theta = [[1],[1],[1]]
# num_iterations = 100
# alpha =0.01
# print(x_train)
print(x_train_scaled)

theta= miniBatchGradientDescent(x_train_scaled,y_train,theta,num_iterations,alpha)
print(theta)

y_pred = getG(np.dot(x_test,theta)) 

for i in range(len(y_pred)):
    if(y_pred[i]>= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
error = 0 

for i in range(len(y_pred)):
    if y_pred[i] != y_test[i]:
        print(y_pred[i],y_test[i])
        error = error+1
error = error/len(y_test)*100
print("Error %age: ",error,"%")

Mini Batch Gradient Descent (without feature scaling)
[[ 0.89888379]
 [ 0.0052166 ]
 [-0.01304646]]
[1.] [0.0]
[0.] [1.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[0.] [1.0]
Error %age:  26.666666666666668 %
Mini Batch Gradient Descent (with feature scaling)
[[1.0, -0.42248191383243333, 0.20129978609183655], [1.0, -0.48514217573552515, -0.29865054135621977], [1.0, -0.40480117908208313, 0.12626269815125174], [1.0, -0.053206205184509116, 0.3226462593950899], [1.0, 0.2191406775841619, 0.1620370549110696], [1.0, -0.2713612948945694, -0.11669549974054327], [1.0, -0.039855306588017794, 0.4721035001464361], [1.0, 0.16123320810088704, -0.2596998294262299], [1.0, 0.17675096051811776, 0.33893569791366374], [1.0, 0.29716112094246266, -0.30394751636894696], [1.0, 0.46228355147646827, -0.3817036736988813], [1.0, 0.1610730204605449, -0.4933550897627231], [1.0, 0.2664480330363781, 0.17870104555494756], [1.0, 0.07945522998911655, 0.4897881898779887], [1.0, -0.35147459588978297, 0.1721802

In [5]:
import numpy as np
from csv import DictReader
import random 

def extract():
    file = open('/content/data.csv', 'r')
    reduced_dict = DictReader(file)
    x = []
    y = []

    for i in reduced_dict:
        x.append([1.0,float(i['Exam 1']),float(i['Exam 2 '])])
        y.append([float(i['Pass/Fail'])])

    x_train = []
    y_train = []
    x_test = []
    y_test = []

    for i in range(len(x)):
        if len(x_train) < 0.7 * len(x):
            x_train.append(x[i])
            y_train.append(y[i])
        else:
            x_test.append(x[i])
            y_test.append(y[i])
    return x_train, y_train, x_test, y_test

def getG(thetax):
#     print("hi",thetax)
    return (1 / (1 + np.exp(-1 * thetax)))

def stochasticGradientDescent(x, y, theta, numIterations,alpha):
    m = len(x)
    for i in range(0, numIterations):
        for k in range(m):
            j = random.randrange(0,m-1)
            start = j
            end = j+1
            X = x[start:end]
            Y = y[start:end]
            xTrans = np.transpose(X)
            hypothesis = getG(np.dot(X, theta))
            loss = hypothesis - Y
            gradient = np.dot(xTrans, loss) / m
            theta = theta - alpha * gradient
    return theta

x_train,y_train,x_test,y_test = extract()

ones = np.ones((len(x_test),1))
theta = [[1],[1],[1]]

num_iterations = 1000
alpha =0.0001

print("Stochastic Gradient Descent (without feature scaling)")
theta= stochasticGradientDescent(x_train,y_train,theta,num_iterations,alpha)
print(theta)

y_pred = getG(np.dot(x_test,theta)) 

for i in range(len(y_pred)):
    if(y_pred[i]>= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
error = 0 

for i in range(len(y_pred)):
    if y_pred[i] != y_test[i]:
        print(y_pred[i],y_test[i])
        error = error+1
error = error/len(y_test)*100

print("Error %age: ",error,"%")

def featureScaling(x_train):

    min_x1 = x_train[0][1]
    min_x2 = x_train[0][2]

    max_x1 = x_train[0][1]
    max_x2 = x_train[0][2]

    x_train_scaled = x_train

    avg_x1 = 0
    avg_x2 = 0

    for i in range(len(x_train)):
        min_x1 = min(x_train[i][1],min_x1)
        min_x2 = min(x_train[i][2],min_x2)
        # min_x3 = min(x_train[i][3],min_x3)

        avg_x1 += x_train[i][1]
        avg_x2 += x_train[i][2]
        # avg_x3 += x_train[i][3]

        max_x1 = max(x_train[i][1],max_x1)
        max_x2 = max(x_train[i][2],max_x2)
        # max_x3 = max(x_train[i][3],max_x3) 

    avg_x1 = avg_x1/len(x_train)
    avg_x2 = avg_x2/len(x_train)
    # avg_x3 = avg_x3/len(x_train)

    for i in range(len(x_train_scaled)):
        x_train_scaled[i][1] = (x_train_scaled[i][1] - avg_x1)/(max_x1-min_x1)
        x_train_scaled[i][2] = (x_train_scaled[i][2] - avg_x2)/(max_x2-min_x2)
        # x_train_scaled[i][3] = (x_train_scaled[i][3] - avg_x3)/(max_x3-min_x3)
    return x_train_scaled

x_train_scaled = featureScaling(x_train)
theta = [[1],[1],[1]]
# num_iterations = 100
# alpha =0.01
# print(x_train)
# print(x_train_scaled)

print("Stochastic Gradient Descent (with feature scaling)")
theta= stochasticGradientDescent(x_train_scaled,y_train,theta,num_iterations,alpha)
print(theta)

y_pred = getG(np.dot(x_test,theta)) 

for i in range(len(y_pred)):
    if(y_pred[i]>= 0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
error = 0 

for i in range(len(y_pred)):
    if y_pred[i] != y_test[i]:
        print(y_pred[i],y_test[i])
        error = error+1
error = error/len(y_test)*100

print("Error %age: ",error,"%")

Stochastic Gradient Descent (without feature scaling)
[[ 0.97584771]
 [ 0.0057593 ]
 [-0.01394054]]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
Error %age:  20.0 %
Stochastic Gradient Descent (with feature scaling)
[[0.97872433]
 [1.00711376]
 [1.00520389]]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
[1.] [0.0]
Error %age:  20.0 %
